// Machine-readable deliverables — the differentiator vs every other logo
// tool on the marketplace. These are what a buyer's coding agent consumes.

import type { Palette } from '../library/palettes';
import type { FontPairing } from '../library/fonts';
import type { ParsedBrief } from '../brief';

export interface TokensInput {
  brief: ParsedBrief;
  palette: Palette;
  pairing: FontPairing;
  slug: string;
}

export function designTokensJson({ brief, palette, pairing, slug }: TokensInput): string {
  return JSON.stringify(
    {
      brand: slug,
      name: brief.businessName,
      tagline: brief.tagline,
      color: {
        primary: palette.primary,
        accent: palette.accent,
        ground: palette.ground,
        ink: palette.ink,
        secondary: palette.secondary,
      },
      type: {
        display: { family: pairing.display.family, weight: pairing.wordmark.weight },
        body: { family: pairing.body.family, weights: pairing.body.weights },
      },
      logo: {
        lockup: 'logo/lockup.svg',
        reversed: 'logo/lockup-reversed.svg',
        mark: 'logo/mark.svg',
        mono: 'logo/mono.svg',
      },
      generatedBy: 'BrandForge on OKX.AI',
    },
    null,
    2,
  );
}

export function brandMarkdown({ brief, palette, pairing }: TokensInput): string {
  return `# ${brief.businessName} — brand spec

**Tagline:** ${brief.tagline}

## Voice
${brief.traits.join(', ')}. Written for: ${brief.audience}.

## Color
- Primary \`${palette.primary}\` — wordmark, headers, hero surfaces.
- Accent \`${palette.accent}\` — calls to action only. One accent element per view.
- Ground \`${palette.ground}\` — page and packaging background.
- Ink \`${palette.ink}\` — running text on ground.
- Secondary \`${palette.secondary}\` — tints, dividers, quiet UI.

${brief.world.rationale}

## Type
- Display: **${pairing.display.family}** (weight ${pairing.wordmark.weight}) — headings only, never below 20px.
- Body: **${pairing.body.family}** — everything else.

## Logo
Clearspace equals the height of the mark. Use the reversed lockup on the primary color. Never stretch, recolor outside this palette, or add a drop shadow.

---
Generated by BrandForge on OKX.AI.
`;
}
